"""
bolsig_input.py — генератор входных файлов для BOLSIG+ (bolsigminus.exe).

Генерирует .dat-файл с параметрами для расчёта транспортных коэффициентов
аргона при заданном давлении и частоте ВЧ-поля.

Usage
-----
  python bolsig_input.py                       # генерирует для давления 1000 Па
  python bolsig_input.py --pressure 5000       # для 5000 Па
  python bolsig_input.py --all                 # для всех давлений из validation_table
"""

import os
import argparse
import numpy as np

# Физические константы
K_BOLTZMANN = 1.380649e-23  # Дж/К

# Путь к базе данных сечений (относительно bolsigplus072024-win/)
CROSS_SECTION_DB = "SigloDataBase-LXCat-04Jun2013.txt"


def generate_bolsig_input(
    p_pa: float,
    omega: float = 2 * np.pi * 1.76e6,
    T_gas: float = 300.0,
    E_N_min: float = 0.1,
    E_N_max: float = 1000.0,
    n_points: int = 50,
    output_file: str = "bolsig_ar_results.dat",
    cross_section_file: str = CROSS_SECTION_DB,
) -> str:
    """
    Генерирует входной файл для bolsigminus.exe.

    Parameters
    ----------
    p_pa            : давление [Па]
    omega           : угловая частота ВЧ-поля [рад/с]
    T_gas           : температура газа [К]
    E_N_min, E_N_max: диапазон E/N [Тд]
    n_points        : число точек в серии
    output_file     : имя выходного файла для результатов BOLSIG+
    cross_section_file : имя файла сечений

    Returns
    -------
    str : содержимое входного файла
    """
    # Концентрация газа
    n_gas = p_pa / (K_BOLTZMANN * T_gas)  # м⁻³

    # Угловая частота / N  [м³/с]
    omega_over_N = omega / n_gas

    lines = []
    lines.append("! BOLSIG+ input — generated by bolsig_input.py")
    lines.append(f"! Pressure: {p_pa:.0f} Pa, T_gas: {T_gas:.0f} K")
    lines.append(f"! omega: {omega:.4e} rad/s, n_gas: {n_gas:.4e} m^-3")
    lines.append(f"! omega/N: {omega_over_N:.4e} m3/s")
    lines.append("")
    lines.append("/NOSCREEN")
    lines.append("")
    lines.append("/NOLOGFILE")
    lines.append("")

    # Чтение сечений для аргона
    lines.append("READCOLLISIONS")
    lines.append(f"{cross_section_file}   / File")
    lines.append("Ar                  / Species")
    lines.append("1                   / Extrapolate: 0= No 1= Yes")
    lines.append("")

    # Условия
    lines.append("CONDITIONS")
    lines.append(f"10.       / Electric field / N (Td)")
    lines.append(f"{omega_over_N:.4e}  / Angular field frequency / N (m3/s)")
    lines.append("0.        / Cosine of E-B field angle")
    lines.append(f"{T_gas:.0f}.      / Gas temperature (K)")
    lines.append(f"{T_gas:.0f}.      / Excitation temperature (K)")
    lines.append("0.        / Transition energy (eV)")
    lines.append("0         / Ionization degree")
    lines.append(f"{n_gas:.4e}  / Gas particle density (1/m3)")
    lines.append("1.        / Ion charge parameter")
    lines.append("1.        / Ion/neutral mass ratio")
    lines.append("3         / e-e momentum effects & modified Coulomb logarithm: 0=No&No; 1=Yes&No; 2=No&Yes; 3=Yes&Yes*")
    lines.append("1         / Energy sharing: 1=Equal*; 2=One takes all")
    lines.append("1         / Growth: 1=Temporal*; 2=Spatial; 3=Not included; 4=Grad-n expansion")
    lines.append("0.        / Maxwellian mean energy (eV)")
    lines.append("400       / # of grid points")
    lines.append("0         / Manual grid: 0=No; 1=Linear; 2=Parabolic")
    lines.append("200.      / Manual maximum energy (eV)")
    lines.append("1e-10     / Precision")
    lines.append("1e-4      / Convergence")
    lines.append("1000      / Maximum # of iterations")
    lines.append("1.        / Gas composition fractions")
    lines.append("1         / Normalize composition to unity: 0=No; 1=Yes")
    lines.append("")

    # Серия расчётов по E/N
    lines.append("RUNSERIES")
    lines.append("1          / Variable: 1=E/N; 2=Mean energy; 3=Maxwellian energy")
    lines.append(f"{E_N_min}  {E_N_max}  / Min Max")
    lines.append(f"{n_points}         / Number")
    lines.append("3          / Type: 1=Linear; 2=Quadratic; 3=Exponential")
    lines.append("")

    # Сохранение результатов
    lines.append("SAVERESULTS")
    lines.append(f"{output_file}        / File")
    lines.append("4        / Format: 1=Run by run; 2=Combined; 3=Separate; 4=E/N; 5=Energy; 6=SIGLO; 7=PLASIMO")
    lines.append("1        / Conditions: 0=No; 1=Yes")
    lines.append("1        / Transport coefficients: 0=No; 1=Yes")
    lines.append("1        / Rate coefficients: 0=No; 1=Yes")
    lines.append("0        / Reverse rate coefficients: 0=No; 1=Yes")
    lines.append("0        / Energy loss coefficients: 0=No; 1=Yes")
    lines.append("0        / Distribution function: 0=No; 1=Yes")
    lines.append("0        / Skip failed runs: 0=No; 1=Yes")
    lines.append("0        / Include cross sections: 0=No; 1=Yes")
    lines.append("")
    lines.append("END")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate BOLSIG+ input files for IDR validation"
    )
    parser.add_argument(
        "--pressure", type=float, default=None,
        help="Pressure in Pa (default: generate for all validation pressures)"
    )
    parser.add_argument(
        "--all", action="store_true",
        help="Generate for all validation pressures (1000, 5000, 10000 Pa)"
    )
    parser.add_argument(
        "--outdir", type=str, default=None,
        help="Output directory (default: bolsigplus072024-win/)"
    )
    args = parser.parse_args()

    # Определяем директории
    base_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(base_dir)
    bolsig_dir = os.path.join(project_root, "bolsigplus072024-win")

    if args.outdir:
        out_dir = args.outdir
    else:
        out_dir = bolsig_dir

    os.makedirs(out_dir, exist_ok=True)

    # Давления
    if args.all or args.pressure is None:
        pressures = [1000.0, 5000.0, 10000.0]
    else:
        pressures = [args.pressure]

    for p_pa in pressures:
        input_name = f"input_ar_{int(p_pa)}Pa.dat"
        output_name = f"bolsig_ar_{int(p_pa)}Pa.dat"

        content = generate_bolsig_input(
            p_pa=p_pa,
            output_file=output_name,
        )

        input_path = os.path.join(out_dir, input_name)
        with open(input_path, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"  [bolsig_input] Generated: {input_path}")
        print(f"                 Results → {output_name}")
        print(f"  Run: cd {bolsig_dir} && bolsigminus.exe < {input_name}")
        print()


if __name__ == "__main__":
    main()
